CREATE TABLE TB_PESSOA 
(
  CODIGO_PESSOA INTEGER NOT NULL,
  NOME VARCHAR(256) NOT NULL,
  SOBRENOME VARCHAR(256) NOT NULL,
  IDADE INTEGER NOT NULL,
  LOGIN VARCHAR(50) NOT NULL,
  SENHA VARCHAR(50) NOT NULL,
  STATUS INTEGER NOT NULL,
  CONSTRAINT TB_PESSOA_PK PRIMARY KEY 
  (
    CODIGO_PESSOA 
  )
);

CREATE TABLE TB_UF 
(
  CODIGO_UF INTEGER NOT NULL,
  SIGLA VARCHAR(3) NOT NULL,
  NOME VARCHAR(60) NOT NULL,
  STATUS INTEGER NOT NULL,
  CONSTRAINT TB_UF_PK PRIMARY KEY 
  (
    CODIGO_UF 
  )
);

CREATE TABLE TB_MUNICIPIO 
(
  CODIGO_MUNICIPIO INTEGER NOT NULL,
  CODIGO_UF INTEGER NOT NULL,
  NOME VARCHAR(256),
  STATUS INTEGER,
  CONSTRAINT TB_MUNICIPIO_PK PRIMARY KEY 
  (
    CODIGO_MUNICIPIO 
  )
);

CREATE TABLE TB_BAIRRO 
(
  CODIGO_BAIRRO INTEGER NOT NULL,
  CODIGO_MUNICIPIO INTEGER NOT NULL,
  NOME VARCHAR(256) NOT NULL,
  STATUS INTEGER,
  CONSTRAINT TB_BAIRRO_PK PRIMARY KEY 
  (
    CODIGO_BAIRRO 
  )
);

CREATE TABLE TB_ENDERECO 
(
  CODIGO_ENDERECO INTEGER NOT NULL,
  CODIGO_PESSOA INTEGER NOT NULL,
  CODIGO_BAIRRO INTEGER NOT NULL,
  NOME_RUA VARCHAR(256) NOT NULL,
  NUMERO VARCHAR(10) NOT NULL,
  COMPLEMENTO VARCHAR(20),
  CEP VARCHAR(10) NOT NULL,
  CONSTRAINT TB_ENDERECO_PK PRIMARY KEY 
  (
    CODIGO_ENDERECO 
  )
);

ALTER TABLE TB_BAIRRO
ADD CONSTRAINT TB_BAIRRO_FK1 FOREIGN KEY
(
  CODIGO_MUNICIPIO 
)
REFERENCES TB_MUNICIPIO
(
  CODIGO_MUNICIPIO 
);

ALTER TABLE TB_ENDERECO
ADD CONSTRAINT TB_ENDERECO_FK1 FOREIGN KEY
(
  CODIGO_PESSOA 
)
REFERENCES TB_PESSOA
(
  CODIGO_PESSOA 
);

ALTER TABLE TB_ENDERECO
ADD CONSTRAINT TB_ENDERECO_FK2 FOREIGN KEY
(
  CODIGO_BAIRRO 
)
REFERENCES TB_BAIRRO
(
  CODIGO_BAIRRO 
);

ALTER TABLE TB_MUNICIPIO
ADD CONSTRAINT TB_MUNICIPIO_FK1 FOREIGN KEY
(
  CODIGO_UF 
)
REFERENCES TB_UF
(
  CODIGO_UF 
);

COMMENT ON COLUMN TB_UF.STATUS IS '1 - ATIVADO
2 - DESATIVADO';

COMMENT ON COLUMN TB_MUNICIPIO.STATUS IS '1 - ATIVADO
2 - DESATIVADO';

COMMENT ON COLUMN TB_BAIRRO.STATUS IS '1- ATIVADO
2- DESATIVADO';

COMMENT ON COLUMN TB_PESSOA.STATUS IS '1 - ATIVADO
2 - DESATIVADO';
